#---------------------------------#
#    environment configuration    #
#---------------------------------#
image:
  - Visual Studio 2019
  - Write-Host "Running on Windows..."  -ForegroundColor "Yellow" -BackgroundColor "DarkYellow"    
  
#---------------------------------#
#       build configuration       #
#---------------------------------#
nuget:  
  disable_publish_on_pr: true 

#---------------------------------#
#       tests configuration       #
#---------------------------------#
test:
  categories:
    only:
      - GetProcessInFormatList
      - GetProcessWithErrorActionInCustomCollection
      - GetProcessByDateRange
      - StopProcessByDateRange

before_deploy:
  - write-host "Running tests :" -foregroundcolor black -backgroundcolor Yellow -nonewline
  - write-host " Vaetech.PowerShell.Tests\Vaetech.PowerShell.Tests.csproj (all frameworks)" -ForegroundColor White -BackgroundColor DarkMagenta
  - Write-Host "dotnet --version:" (dotnet --version) -ForegroundColor "Yellow"

test_script:
  - dotnet test "Vaetech.PowerShell.Tests\Vaetech.PowerShell.Tests.csproj" -c Release --no-build
  - Write-Host "Done testing." -ForegroundColor "Green"