image: 
 - Visual Studio 2019
# - Ubuntu
  
environment:
  Appveyor: true

init:
  - git config --global core.autocrlf input

nuget:  
  disable_publish_on_pr: true 

build_script:
  - ps: .\build.ps1 -PullRequestNumber "$env:APPVEYOR_PULL_REQUEST_NUMBER" -CreatePackages $true

test: off