image: Visual Studio 2019  
  
environment:
  Appveyor: true

init:
  - git config --global core.autocrlf input

nuget:  
  disable_publish_on_pr: true 

before_test:
  - ps: Write-Host "dotnet --version:" (dotnet --version) -ForegroundColor "Yellow"

test_script:
  - dotnet test "Vaetech.PowerShell.Tests\Vaetech.PowerShell.Tests.csproj" -c Release --no-build
  - ps: Write-Host "Done testing." -ForegroundColor "Green"